-- Supabase schema for the Agent Search scraper.
-- Run this in your Supabase project: SQL Editor -> New query -> paste -> Run.
-- Re-scraping a market UPDATES existing rows (upsert on the primary key) instead
-- of creating duplicates.

-- courted
create table if not exists courted_agents (
    name text,
    first_name text,
    last_name text,
    nickname text,
    email text,
    phone text,
    mobile_phone text,
    saved_contact_info text,
    profile_photo_url text,
    courted_profile_url text,
    courted_agent_id text,
    courted_id text primary key,
    member_mls_id text,
    office text,
    custom_office_name text,
    brand text,
    office_address text,
    office_city text,
    office_state text,
    office_zip text,
    time_at_current_office_mos text,
    avg_time_at_office_mos text,
    years_of_experience text,
    agent_tenure_mos text,
    is_new_agent text,
    ltm_sales_volume text,
    prev_ltm_sales_volume text,
    sales_volume_change_pct text,
    ltm_est_gci text,
    ltm_avg_sale_price text,
    ltm_closed_transactions text,
    ltm_closed_units text,
    ltm_units_buy_side text,
    ltm_units_list_side text,
    ltm_sales_volume_buy_side text,
    ltm_sales_volume_list_side text,
    ltm_avg_sale_price_buy_side text,
    ltm_avg_sale_price_list_side text,
    ltm_close_to_list_price_pct text,
    ltm_avg_days_on_market text,
    ltm_rental_count text,
    ltm_avg_rental_price text,
    ytd_sales_volume text,
    ytd_units text,
    ytd_avg_sale_price text,
    active_listings text,
    pending_listings text,
    sales_volume_prediction text,
    prediction_low text,
    prediction_high text,
    likelihood_to_move text,
    future_growth_tag text,
    forecast_segment text,
    ai_agent_type text,
    most_transacted_city text,
    most_transacted_state text,
    most_transacted_zip text,
    mls text,
    mls_id text,
    state_license text,
    alt_state_licenses text,
    mls_affiliations text,
    is_team_leader text,
    is_team_member text,
    is_managing_broker text,
    is_rental_agent text,
    home_address text,
    home_city text,
    home_state text,
    home_zip text,
    prospect_status text,
    assigned_to text,
    connections text,
    is_watching text,
    is_liked text,
    searched_location text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- zillow
create table if not exists zillow_agents (
    name text,
    brokerage text,
    phone text,
    email text,
    rating text,
    review_count text,
    total_sales_count text,
    active_listings_count text,
    for_sale_count text,
    for_rent_count text,
    sold_count text,
    specialties text,
    service_areas text,
    years_of_experience text,
    languages_spoken text,
    location text,
    city text,
    state text,
    zip_code text,
    profile_photo_url text,
    zillow_profile_url text primary key,
    top_agent_on_zillow text,
    is_team text,
    team_name text,
    team_member_count text,
    average_sales_volume text,
    average_price text,
    sales_count_last_year text,
    premier_agent text,
    local_sales_count text,
    legal_name text,
    title text,
    address text,
    brokerage_address text,
    website_url text,
    facebook_url text,
    linkedin_url text,
    instagram_url text,
    twitter_url text,
    youtube_url text,
    pinterest_url text,
    license_number text,
    license_state text,
    license_description text,
    all_licenses text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- mls_monitor_state — server-side baseline for the automatic ("Option B") MLS
-- watch: one row per Courted login account holding its last-seen MLS list. The
-- scheduler diffs a fresh scan against this and alerts on any add / remove.
-- Additive-only; touches no agent data.
create table if not exists mls_monitor_state (
    email text primary key,
    mls jsonb not null default '[]'::jsonb,   -- [{ code, name, count }]
    total integer not null default 0,
    scanned_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- refresh_state — progress store for the automatic ("15-day") refresh: one row
-- per Courted login account holding when it was last fully re-scraped. The
-- scheduler picks whichever account has gone longest without a refresh, so every
-- account (and thus every agent it can see) is re-pulled within the window.
-- Re-scraping ACCUMULATES (adds/updates, never deletes) — additive-only.
create table if not exists refresh_state (
    email text primary key,
    last_refreshed_at timestamptz,
    last_status text,                          -- 'ok' | 'error'
    last_message text,
    updated_at timestamptz not null default now()
);

-- realtor
create table if not exists realtor_agents (
    name text,
    first_name text,
    last_name text,
    phone text,
    mobile_phone text,
    email text,
    office text,
    broker text,
    office_address text,
    office_city text,
    office_state text,
    office_postal text,
    rating text,
    review_count text,
    recommendations text,
    years_of_experience text,
    experience_since text,
    languages text,
    specializations text,
    designations text,
    served_areas text,
    for_sale_count text,
    for_sale_price_range text,
    sold_count text,
    sold_price_range text,
    last_sold_date text,
    combined_price_range text,
    license_number text,
    license_state text,
    mls text,
    website_url text,
    facebook_url text,
    instagram_url text,
    linkedin_url text,
    twitter_url text,
    youtube_url text,
    tiktok_url text,
    profile_photo_url text,
    bio text,
    is_realtor text,
    is_advertiser text,
    realtor_profile_url text primary key,
    realtor_agent_id text,
    fulfillment_id text,
    searched_location text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
